# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  imgui_config = debug
  window_config = debug
endif
ifeq ($(config),release)
  imgui_config = release
  window_config = release
endif

PROJECTS := imgui window

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

imgui:
ifneq (,$(imgui_config))
	@echo "==== Building imgui ($(imgui_config)) ===="
	@${MAKE} --no-print-directory -C . -f imgui.make config=$(imgui_config)
endif

window: imgui
ifneq (,$(window_config))
	@echo "==== Building window ($(window_config)) ===="
	@${MAKE} --no-print-directory -C . -f window.make config=$(window_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f imgui.make clean
	@${MAKE} --no-print-directory -C . -f window.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   imgui"
	@echo "   window"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"